# Generated by Django 6.1 on 2026-08-30 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnsembleForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, unique=True)),
                ("issued_at", models.DateTimeField(db_index=True)),
                ("knmi_created", models.DateTimeField(blank=True, null=True)),
                ("knmi_last_modified", models.DateTimeField(blank=True, null=True)),
                ("size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("file_path", models.CharField(max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("downloaded", "Downloaded"),
                            ("parsed", "Parsed"),
                            ("failed", "Failed"),
                        ],
                        default="downloaded",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("rows", models.PositiveIntegerField(blank=True, null=True)),
                ("cols", models.PositiveIntegerField(blank=True, null=True)),
                ("proj4", models.TextField(blank=True)),
                (
                    "member_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="EnsembleForecastStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lead_minutes", models.PositiveSmallIntegerField()),
                ("valid_at", models.DateTimeField()),
                (
                    "forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="radar.ensembleforecast",
                    ),
                ),
            ],
            options={
                "ordering": ["lead_minutes"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("forecast", "lead_minutes"),
                        name="unique_ensemble_forecast_lead_minutes",
                    )
                ],
            },
        ),
    ]
