# Generated by Django 6.1 on 2026-09-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0002_ensembleforecast_ensembleforecaststep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ensembleforecast",
            name="status",
            field=models.CharField(
                choices=[
                    ("downloaded", "Gedownload"),
                    ("parsed", "Verwerkt"),
                    ("failed", "Mislukt"),
                ],
                default="downloaded",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="radarforecast",
            name="status",
            field=models.CharField(
                choices=[
                    ("downloaded", "Gedownload"),
                    ("parsed", "Verwerkt"),
                    ("failed", "Mislukt"),
                ],
                default="downloaded",
                max_length=16,
            ),
        ),
    ]
