# Generated by Django 6.1 on 2026-09-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0003_alter_ensembleforecast_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnsembleIngestState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finished_at", models.DateTimeField()),
                ("success", models.BooleanField()),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Ensemble-ingeststatus",
                "verbose_name_plural": "Ensemble-ingeststatus",
            },
        ),
    ]
